services:
  postgres:
    build: "."
    image: postgres-pgcron:16.4
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
